#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias poweroff='sudo poweroff'
alias reboot='sudo reboot'
alias off='sudo poweroff'

export LC_CTYPE="en_US.utf8"

PS1='[\u@\h \W]\$ '

if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
	exec startx
fi
