#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# change capslock to escape

xmodmap -e 'keycode 135 = Super_R' &

# start some nice programs

if [ -d ~/xinitrc.d ] ; then
 for f in ~/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#nitrogen --restore &
dxhd -b &
urxvtd --quiet --opendisplay --fork &
exec dbus-launch --sh-syntax --exit-with-session dwm
